/**
 * @fileoverview ISO 3166-1 alpha-2 ↔ alpha-3 table (the 249 officially assigned
 * codes), the `country` input normalizer, the alpha-2 validity check, and
 * English display names. The bundled table is the only source of code validity;
 * `Intl.DisplayNames` supplies names but cannot validate, since it names
 * unassigned codes too.
 * @module services/unesco-datahub/iso3166
 */

/** Officially assigned ISO 3166-1 codes as `[alpha2, alpha3]` pairs. */
export const ISO_3166_PAIRS: readonly (readonly [string, string])[] = [
  ['AD', 'AND'],
  ['AE', 'ARE'],
  ['AF', 'AFG'],
  ['AG', 'ATG'],
  ['AI', 'AIA'],
  ['AL', 'ALB'],
  ['AM', 'ARM'],
  ['AO', 'AGO'],
  ['AQ', 'ATA'],
  ['AR', 'ARG'],
  ['AS', 'ASM'],
  ['AT', 'AUT'],
  ['AU', 'AUS'],
  ['AW', 'ABW'],
  ['AX', 'ALA'],
  ['AZ', 'AZE'],
  ['BA', 'BIH'],
  ['BB', 'BRB'],
  ['BD', 'BGD'],
  ['BE', 'BEL'],
  ['BF', 'BFA'],
  ['BG', 'BGR'],
  ['BH', 'BHR'],
  ['BI', 'BDI'],
  ['BJ', 'BEN'],
  ['BL', 'BLM'],
  ['BM', 'BMU'],
  ['BN', 'BRN'],
  ['BO', 'BOL'],
  ['BQ', 'BES'],
  ['BR', 'BRA'],
  ['BS', 'BHS'],
  ['BT', 'BTN'],
  ['BV', 'BVT'],
  ['BW', 'BWA'],
  ['BY', 'BLR'],
  ['BZ', 'BLZ'],
  ['CA', 'CAN'],
  ['CC', 'CCK'],
  ['CD', 'COD'],
  ['CF', 'CAF'],
  ['CG', 'COG'],
  ['CH', 'CHE'],
  ['CI', 'CIV'],
  ['CK', 'COK'],
  ['CL', 'CHL'],
  ['CM', 'CMR'],
  ['CN', 'CHN'],
  ['CO', 'COL'],
  ['CR', 'CRI'],
  ['CU', 'CUB'],
  ['CV', 'CPV'],
  ['CW', 'CUW'],
  ['CX', 'CXR'],
  ['CY', 'CYP'],
  ['CZ', 'CZE'],
  ['DE', 'DEU'],
  ['DJ', 'DJI'],
  ['DK', 'DNK'],
  ['DM', 'DMA'],
  ['DO', 'DOM'],
  ['DZ', 'DZA'],
  ['EC', 'ECU'],
  ['EE', 'EST'],
  ['EG', 'EGY'],
  ['EH', 'ESH'],
  ['ER', 'ERI'],
  ['ES', 'ESP'],
  ['ET', 'ETH'],
  ['FI', 'FIN'],
  ['FJ', 'FJI'],
  ['FK', 'FLK'],
  ['FM', 'FSM'],
  ['FO', 'FRO'],
  ['FR', 'FRA'],
  ['GA', 'GAB'],
  ['GB', 'GBR'],
  ['GD', 'GRD'],
  ['GE', 'GEO'],
  ['GF', 'GUF'],
  ['GG', 'GGY'],
  ['GH', 'GHA'],
  ['GI', 'GIB'],
  ['GL', 'GRL'],
  ['GM', 'GMB'],
  ['GN', 'GIN'],
  ['GP', 'GLP'],
  ['GQ', 'GNQ'],
  ['GR', 'GRC'],
  ['GS', 'SGS'],
  ['GT', 'GTM'],
  ['GU', 'GUM'],
  ['GW', 'GNB'],
  ['GY', 'GUY'],
  ['HK', 'HKG'],
  ['HM', 'HMD'],
  ['HN', 'HND'],
  ['HR', 'HRV'],
  ['HT', 'HTI'],
  ['HU', 'HUN'],
  ['ID', 'IDN'],
  ['IE', 'IRL'],
  ['IL', 'ISR'],
  ['IM', 'IMN'],
  ['IN', 'IND'],
  ['IO', 'IOT'],
  ['IQ', 'IRQ'],
  ['IR', 'IRN'],
  ['IS', 'ISL'],
  ['IT', 'ITA'],
  ['JE', 'JEY'],
  ['JM', 'JAM'],
  ['JO', 'JOR'],
  ['JP', 'JPN'],
  ['KE', 'KEN'],
  ['KG', 'KGZ'],
  ['KH', 'KHM'],
  ['KI', 'KIR'],
  ['KM', 'COM'],
  ['KN', 'KNA'],
  ['KP', 'PRK'],
  ['KR', 'KOR'],
  ['KW', 'KWT'],
  ['KY', 'CYM'],
  ['KZ', 'KAZ'],
  ['LA', 'LAO'],
  ['LB', 'LBN'],
  ['LC', 'LCA'],
  ['LI', 'LIE'],
  ['LK', 'LKA'],
  ['LR', 'LBR'],
  ['LS', 'LSO'],
  ['LT', 'LTU'],
  ['LU', 'LUX'],
  ['LV', 'LVA'],
  ['LY', 'LBY'],
  ['MA', 'MAR'],
  ['MC', 'MCO'],
  ['MD', 'MDA'],
  ['ME', 'MNE'],
  ['MF', 'MAF'],
  ['MG', 'MDG'],
  ['MH', 'MHL'],
  ['MK', 'MKD'],
  ['ML', 'MLI'],
  ['MM', 'MMR'],
  ['MN', 'MNG'],
  ['MO', 'MAC'],
  ['MP', 'MNP'],
  ['MQ', 'MTQ'],
  ['MR', 'MRT'],
  ['MS', 'MSR'],
  ['MT', 'MLT'],
  ['MU', 'MUS'],
  ['MV', 'MDV'],
  ['MW', 'MWI'],
  ['MX', 'MEX'],
  ['MY', 'MYS'],
  ['MZ', 'MOZ'],
  ['NA', 'NAM'],
  ['NC', 'NCL'],
  ['NE', 'NER'],
  ['NF', 'NFK'],
  ['NG', 'NGA'],
  ['NI', 'NIC'],
  ['NL', 'NLD'],
  ['NO', 'NOR'],
  ['NP', 'NPL'],
  ['NR', 'NRU'],
  ['NU', 'NIU'],
  ['NZ', 'NZL'],
  ['OM', 'OMN'],
  ['PA', 'PAN'],
  ['PE', 'PER'],
  ['PF', 'PYF'],
  ['PG', 'PNG'],
  ['PH', 'PHL'],
  ['PK', 'PAK'],
  ['PL', 'POL'],
  ['PM', 'SPM'],
  ['PN', 'PCN'],
  ['PR', 'PRI'],
  ['PS', 'PSE'],
  ['PT', 'PRT'],
  ['PW', 'PLW'],
  ['PY', 'PRY'],
  ['QA', 'QAT'],
  ['RE', 'REU'],
  ['RO', 'ROU'],
  ['RS', 'SRB'],
  ['RU', 'RUS'],
  ['RW', 'RWA'],
  ['SA', 'SAU'],
  ['SB', 'SLB'],
  ['SC', 'SYC'],
  ['SD', 'SDN'],
  ['SE', 'SWE'],
  ['SG', 'SGP'],
  ['SH', 'SHN'],
  ['SI', 'SVN'],
  ['SJ', 'SJM'],
  ['SK', 'SVK'],
  ['SL', 'SLE'],
  ['SM', 'SMR'],
  ['SN', 'SEN'],
  ['SO', 'SOM'],
  ['SR', 'SUR'],
  ['SS', 'SSD'],
  ['ST', 'STP'],
  ['SV', 'SLV'],
  ['SX', 'SXM'],
  ['SY', 'SYR'],
  ['SZ', 'SWZ'],
  ['TC', 'TCA'],
  ['TD', 'TCD'],
  ['TF', 'ATF'],
  ['TG', 'TGO'],
  ['TH', 'THA'],
  ['TJ', 'TJK'],
  ['TK', 'TKL'],
  ['TL', 'TLS'],
  ['TM', 'TKM'],
  ['TN', 'TUN'],
  ['TO', 'TON'],
  ['TR', 'TUR'],
  ['TT', 'TTO'],
  ['TV', 'TUV'],
  ['TW', 'TWN'],
  ['TZ', 'TZA'],
  ['UA', 'UKR'],
  ['UG', 'UGA'],
  ['UM', 'UMI'],
  ['US', 'USA'],
  ['UY', 'URY'],
  ['UZ', 'UZB'],
  ['VA', 'VAT'],
  ['VC', 'VCT'],
  ['VE', 'VEN'],
  ['VG', 'VGB'],
  ['VI', 'VIR'],
  ['VN', 'VNM'],
  ['VU', 'VUT'],
  ['WF', 'WLF'],
  ['WS', 'WSM'],
  ['YE', 'YEM'],
  ['YT', 'MYT'],
  ['ZA', 'ZAF'],
  ['ZM', 'ZMB'],
  ['ZW', 'ZWE'],
];

const ALPHA2_TO_ALPHA3 = new Map(ISO_3166_PAIRS.map(([a2, a3]) => [a2, a3]));
const ALPHA3_TO_ALPHA2 = new Map(ISO_3166_PAIRS.map(([a2, a3]) => [a3, a2]));

const displayNames = new Intl.DisplayNames(['en'], { type: 'region' });

/**
 * Schema preprocess for `country` inputs. Trims; uppercases a two- or
 * three-letter ASCII value; maps `UK` to `GB`; maps an assigned alpha-3 code to
 * its alpha-2 code. Anything else passes through (trimmed) for the handler's
 * validity check to reject with its recovery hint.
 */
export function normalizeCountry(value: unknown): unknown {
  if (typeof value !== 'string') return value;
  const trimmed = value.trim();
  if (!/^[A-Za-z]{2,3}$/.test(trimmed)) return trimmed;
  const upper = trimmed.toUpperCase();
  if (upper === 'UK') return 'GB';
  return upper.length === 3 ? (ALPHA3_TO_ALPHA2.get(upper) ?? upper) : upper;
}

/** True when `code` is an officially assigned ISO 3166-1 alpha-2 code. */
export function isAssignedAlpha2(code: string): boolean {
  return ALPHA2_TO_ALPHA3.has(code);
}

/** The alpha-3 code for an assigned alpha-2 code. */
export function alpha3Of(code: string): string | undefined {
  return ALPHA2_TO_ALPHA3.get(code);
}

/** English display name for an alpha-2 code, falling back to the code itself. */
export function countryDisplayName(code: string): string {
  return displayNames.of(code) ?? code;
}
